"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!qhrlvuq52**75y8+tysa2@q129ke2zb9a253em#!$wi9l^y*q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracking.apps.TrackingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sample_tracking',
        'USER': 'postgres',
        'PASSWORD': 'lonely',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


USSD_DOWNLOAD_DIR = BASE_DIR / "downloads" / "ussd"


USSD_EXPORT_URL = "http://206.225.84.201/r4h_new/all_sample_collection_summaries_export.php"

USSD_USERNAME = "riders"
USSD_PASSWORD = "health"


COMMCARE_DOMAIN = "sample-22"
COMMCARE_USERNAME = "lchisale@r4hmw.org"
COMMCARE_API_KEY = "1Blantyre@"


# settings.py

GOOGLE_SHEET_ID = "1bIGKdn8bMmFYhucGvf0FfdbOF36ZzeaYZmN7qfexrXE"

GOOGLE_WORKSHEET_NAME = "Outbreak Tracking"

GOOGLE_CREDENTIALS_FILE = (
    BASE_DIR / "auth.json"
)



TENANT_ID = "23f77dfe-b0f2-4fb1-a637-30729a262d24"

CLIENT_ID = "bbc0ef57-7815-4cdd-be90-14567644b238"

CLIENT_SECRET = "Nnl8Q~Oj6nYXi7YXjQ2AGnm1tPXrK~YcCFFVhc~4"

SITE_ID = (
    "r4hmw.sharepoint.com,"
    "9be3cce0-3385-4daa-bbe3-d47245ff8aea,"
    "43b835f7-9e31-4bbe-90e3-cb53e6d5b447"
)

DRIVE_ID = (
    "b!4Mzjm4Uzqk2749RyRf-K6vc1uEMxnr5LkOPLU-bVtEc6C-l7L9JqRZKLY3GIubLu"
)