# Generated by Django 5.2.15 on 2026-06-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommCareTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, max_length=100)),
                ('picked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_by', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidatedSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('ussd_code', models.CharField(blank=True, max_length=100, null=True)),
                ('date_reported', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.CharField(blank=True, max_length=255, null=True)),
                ('testing_lab', models.CharField(blank=True, max_length=255, null=True)),
                ('picked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_by', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='USSDSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ussd_code', models.CharField(max_length=100, unique=True)),
                ('tracking_number', models.CharField(db_index=True, max_length=100)),
                ('date_reported', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.CharField(blank=True, max_length=255, null=True)),
                ('testing_lab', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
