# Generated by Django 5.2.15 on 2026-06-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ussdsample',
            old_name='testing_lab',
            new_name='facility',
        ),
        migrations.RemoveField(
            model_name='ussdsample',
            name='ussd_code',
        ),
        migrations.AddField(
            model_name='ussdsample',
            name='coc_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ussdsample',
            name='collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ussdsample',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ussdsample',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ussdsample',
            name='sample',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ussdsample',
            name='sample_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ussdsample',
            name='ussd_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ussdsample',
            name='reported_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
