# Generated by Django 5.2.15 on 2026-06-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_rename_testing_lab_ussdsample_facility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommCareSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=255, unique=True)),
                ('sample_barcode', models.CharField(db_index=True, max_length=100)),
                ('facility_name', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('test_requested', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_status', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('date_sample_collected_from_patient', models.DateField(blank=True, null=True)),
                ('date_sample_picked_up_by_courier', models.DateField(blank=True, null=True)),
                ('date_sample_delivered_to_molecular_lab', models.DateField(blank=True, null=True)),
                ('date_result_delivered_to_facility', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CommCareTransport',
        ),
        migrations.AlterField(
            model_name='ussdsample',
            name='ussd_id',
            field=models.IntegerField(unique=True),
        ),
    ]
