# Generated by Django 5.2.15 on 2026-06-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_commcaresample_delete_commcaretransport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commcaresample',
            name='sample_barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
