# Generated by Django 5.2.15 on 2026-06-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_commcaresample_sample_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50, unique=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='commcaresample',
            name='delivered_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commcaresample',
            name='lab_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commcaresample',
            name='picked_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commcaresample',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commcaresample',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
