# Generated by Django 5.2.15 on 2026-06-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_synclog_commcaresample_delivered_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consolidatedsample',
            old_name='delivered_by',
            new_name='collected_by',
        ),
        migrations.RenameField(
            model_name='consolidatedsample',
            old_name='picked_by',
            new_name='collection_location',
        ),
        migrations.RenameField(
            model_name='consolidatedsample',
            old_name='date_reported',
            new_name='date_of_notification',
        ),
        migrations.RenameField(
            model_name='consolidatedsample',
            old_name='reported_by',
            new_name='delivery_location',
        ),
        migrations.RenameField(
            model_name='consolidatedsample',
            old_name='ussd_code',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='consolidatedsample',
            old_name='testing_lab',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='consolidatedsample',
            old_name='tracking_number',
            new_name='waybill_number',
        ),
        migrations.RemoveField(
            model_name='consolidatedsample',
            name='delivered_time',
        ),
        migrations.RemoveField(
            model_name='consolidatedsample',
            name='pickup_time',
        ),
        migrations.AddField(
            model_name='consolidatedsample',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consolidatedsample',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consolidatedsample',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consolidatedsample',
            name='shipment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consolidatedsample',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consolidatedsample',
            name='ussd_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
