# Generated by Django 5.2.15 on 2026-07-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_rename_delivered_by_consolidatedsample_collected_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consolidatedsample',
            old_name='shipment_type',
            new_name='Sample_subtype',
        ),
        migrations.RenameField(
            model_name='consolidatedsample',
            old_name='collected_by',
            new_name='picked_by',
        ),
        migrations.RenameField(
            model_name='consolidatedsample',
            old_name='collection_date',
            new_name='pickup_date',
        ),
        migrations.RenameField(
            model_name='consolidatedsample',
            old_name='collection_location',
            new_name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='consolidatedsample',
            name='waybill_number',
        ),
        migrations.AddField(
            model_name='commcaresample',
            name='receivedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commcaresample',
            name='receivedbyphonenumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consolidatedsample',
            name='Sample_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consolidatedsample',
            name='Sample_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consolidatedsample',
            name='coc_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consolidatedsample',
            name='receivedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consolidatedsample',
            name='receivedbyphonenumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consolidatedsample',
            name='reported_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consolidatedsample',
            name='ussd_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
