# Generated by Django 5.2.15 on 2026-07-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_rename_shipment_type_consolidatedsample_sample_subtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidatedsample',
            name='ussd_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
